### PR TITLE
Ot296 36

### PR DESCRIPTION
**Pull request by EzequielAlva**
Summary:

- functionality added: GET all user's information by an ADMIN user
- RoleDTO added (to return user's role information)
- RoleMapper added (idem)
- UserWithoutPassDTO added (to return information without user's password)
- UserWithoutPassMapper added (idem)

### CODE REVIEW

**Review by flavioambroggio — APPROVED** [review]
Visto y aprobado.

**Review by juan1977lopez — COMMENTED** [review]
Favor revisar conflictos

**Comment by EzequielAlva** [comment]
Resolved Conflict

**Comment by EzequielAlva** [comment]
Merge problems fixed

**Pull request merged**
