### PR TITLE
OT296-73 Create a Seeder to populate the database with Users for testing

### PR DESCRIPTION
**Pull request by macarogo**
Tuve que agregar constructor a Users y Role

### CODE REVIEW

**Comment by macarogo** [comment]
BbddUsers

**Comment by macarogo** [comment]
BbddRole

**Review by flavioambroggio — APPROVED** [review]
Visto y aprobado.

**Review by gabibosio — APPROVED** [review]
Aprobado

**Review by EzequielAlva — APPROVED** [review]
Correcto...

**Pull request merged**
